# Generated by Django 5.2.4 on 2025-09-23 13:59

import colorfield.fields
import core.models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import location_field.models.plain
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarruselImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen', models.ImageField(default='default_image.png', upload_to='')),
                ('texto', models.TextField(blank=True, null=True)),
                ('color_texto', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black')])),
                ('color_fondo', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=[('#FFFFFF', 'white'), ('#000000', 'black')])),
            ],
            options={
                'verbose_name': 'Flayer/Imagen',
                'verbose_name_plural': 'Cartel Carrousel',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(max_length=12)),
                ('mensaje', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes de Contacto',
            },
        ),
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('count', models.IntegerField(default=0, verbose_name='Número de visitas al sitio web')),
            ],
            options={
                'verbose_name': 'Estadísticas de visitas diarias al sitio web',
                'verbose_name_plural': 'Estadísticas de visitas diarias al sitio web',
            },
        ),
        migrations.CreateModel(
            name='GrillaExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=core.models.up_doc)),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Planilla Excel/CSV',
                'verbose_name_plural': 'Plantillas Excel/CSV',
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('mostrar', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria/Rubros',
                'verbose_name_plural': 'Categorias/Rubros de Productos',
            },
        ),
        migrations.CreateModel(
            name='MercadoPagoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('public_key', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('client_secret', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cuenta de cobro',
                'verbose_name_plural': 'Cuentas MercadoPago',
            },
        ),
        migrations.CreateModel(
            name='OrdenCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_orden', models.CharField(choices=[('categoria', 'Por Categoría (A-Z)'), ('-categoria', 'Por Categoría (Z-A)'), ('marca', 'Por Marca (A-Z)'), ('-marca', 'Por Marca (Z-A)'), ('nombre', 'Por Nombre (A-Z)'), ('-nombre', 'Por Nombre (Z-A)'), ('precio', 'Por Precio (Menor a Mayor)'), ('-precio', 'Por Precio (Mayor a Menor)'), ('id', 'Por ID (Más Antiguo)'), ('-id', 'Por ID (Más Nuevo)')], default='categoria', max_length=20, verbose_name='Campo de Ordenamiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orden del Catálogo',
                'verbose_name_plural': 'Órdenes del Catálogo',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=12)),
                ('ubicacion', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='Dirección IP')),
                ('count', models.IntegerField(default=0, verbose_name='Visitas')),
            ],
            options={
                'verbose_name': 'Acceder a la información del usuario',
                'verbose_name_plural': 'Acceder a la información del usuario',
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Total de visitas al sitio web')),
            ],
            options={
                'verbose_name': 'Total de visitas al sitio web',
                'verbose_name_plural': 'Total de visitas al sitio web',
            },
        ),
        migrations.CreateModel(
            name='CargaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Carrito')),
            ],
            options={
                'verbose_name': 'Carrito del usuario',
                'verbose_name_plural': 'Carrito de:',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.maincategory')),
            ],
            options={
                'verbose_name': 'SubCategoria',
                'verbose_name_plural': 'SubCategoria de Productos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('total_cantidad', models.PositiveIntegerField(default=0, verbose_name='Total de Cantidad')),
                ('total_precio', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Total de Precio')),
                ('pagado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('vendedor', models.ForeignKey(blank=True, help_text='Vendedor asignado al pedido', limit_choices_to=models.Q(('groups__name', 'vendedor'), ('groups__name', 'admin'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='/static/img/usuario_defecto.webp', null=True, upload_to='usuarios/', verbose_name='Imagen de perfil')),
                ('direccion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('localidad', models.CharField(blank=True, max_length=150, null=True, verbose_name='Barrio/Cuidad')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('vendedor', 'Vendedor'), ('admin', 'Administrador')], default='cliente', max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ClienteVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_vendedores', to='core.perfil')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_relacionados', to='core.perfil')),
            ],
            options={
                'verbose_name': 'Cliente/Vendedor',
                'verbose_name_plural': 'Vendedores Asignados',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Descripcion')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('imagen1', models.ImageField(default='default_image.png', upload_to='')),
                ('imagen2', models.ImageField(default='default_image.png', upload_to='')),
                ('imagenurl', models.URLField(blank=True, max_length=20000, null=True)),
                ('stock', models.PositiveIntegerField(default=0, null=True)),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('numero', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_x_pack', models.PositiveIntegerField(blank=True, default=0)),
                ('precio_m', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('carga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizado', to='core.cargaarchivo')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='core.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.PositiveIntegerField(default=0, verbose_name='Descuento de oferta')),
                ('precio_anterior', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('precio_final', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='en_oferta', to='core.product')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas de Productos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Subtotal')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cart', verbose_name='Carrito')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pedido', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto en Carrito',
                'verbose_name_plural': 'Productos en Carrito',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='core.CartItem', to='core.product', verbose_name='Productos'),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vigencia', models.DateTimeField(blank=True, null=True)),
                ('base', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name': 'Promociones',
                'verbose_name_plural': 'Promos',
            },
        ),
    ]
