# Generated by Django 5.2.4 on 2025-09-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="contador_carrito",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="contador_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
