# Generated by Django 4.2.5 on 2025-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_contador_carrito_product_contador_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google ID'),
        ),
    ]
