# Generated by Django 4.2.5 on 2025-12-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfil_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='es_oauth',
            field=models.BooleanField(default=False, verbose_name='Usuario OAuth'),
        ),
    ]
