# Generated by Django 4.2.5 on 2025-12-13 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil_es_oauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Oferta activa'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='monto_combinar',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Monto del combo'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='producto_combinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combinado_con', to='core.product', verbose_name='Producto a combinar'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_multiplicidad',
            field=models.CharField(blank=True, choices=[('2x1', '2x1 - Lleva 2, paga 1'), ('3x2', '3x2 - Lleva 3, paga 2'), ('4x3', '4x3 - Lleva 4, paga 3'), ('5x4', '5x4 - Lleva 5, paga 4')], max_length=10, null=True, verbose_name='Tipo de multiplicidad'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_oferta',
            field=models.CharField(choices=[('descuento', 'Descuento Porcentual'), ('combinar', 'Combinar con Producto'), ('multiplicidad', '2x1, 3x2, etc.')], default='descuento', max_length=20),
        ),
    ]
