# Generated by Django 4.2.5 on 2025-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_oferta_activa_oferta_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='duracion_dias',
            field=models.PositiveIntegerField(default=30, help_text='Duración de la oferta en días desde su creación', verbose_name='Duración en días'),
        ),
    ]
