# Generated by Django 4.2.5 on 2025-12-13 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_duracion_dias_to_oferta'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('retiro_tienda', 'Retiro en Tienda'), ('envio_domicilio', 'Envío a Domicilio'), ('envio_gratis', 'Envío Gratis'), ('retiro_sucursal', 'Retiro en Sucursal')], default='retiro_tienda', max_length=20, verbose_name='Tipo de envío')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la opción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('costo', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Costo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tiempo_entrega', models.CharField(blank=True, max_length=50, verbose_name='Tiempo de entrega')),
            ],
            options={
                'verbose_name': 'Opción de Envío',
                'verbose_name_plural': 'Opciones de Envío',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='opcion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.opcionenvio', verbose_name='Opción de envío'),
        ),
    ]
