# Generated by Django 4.2.5 on 2025-12-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_opcionenvio_pedido_costo_envio_pedido_opcion_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido', 'Nuevo Pedido'), ('compra', 'Nueva Compra'), ('contacto', 'Mensaje de Contacto'), ('producto', 'Producto Agotado'), ('oferta', 'Nueva Oferta Creada'), ('usuario', 'Nuevo Usuario Registrado'), ('sistema', 'Alerta del Sistema')], max_length=20, verbose_name='Tipo de Notificación')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('referencia_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de Referencia')),
                ('referencia_tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Referencia')),
            ],
            options={
                'verbose_name': 'Notificación Administrativa',
                'verbose_name_plural': 'Notificaciones Administrativas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
