# Generated by Django 4.2.5 on 2025-12-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_notificacionadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono de contacto')),
                ('vehiculo', models.CharField(max_length=100, verbose_name='Tipo de vehículo')),
                ('patente', models.CharField(max_length=10, verbose_name='Patente del vehículo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario transportista')),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de asignación'), ('asignado', 'Asignado a transportista'), ('en_transito', 'En tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del envío')),
                ('qr_code', models.CharField(max_length=255, unique=True, verbose_name='Código QR')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de entrega')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pedido', verbose_name='Pedido asociado')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transportista', verbose_name='Transportista asignado')),
            ],
            options={
                'verbose_name': 'Envío',
                'verbose_name_plural': 'Envíos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de confirmación')),
                ('qr_escaneado', models.CharField(max_length=255, verbose_name='QR escaneado')),
                ('ubicacion_gps', models.CharField(blank=True, max_length=255, verbose_name='Ubicación GPS')),
                ('foto_entrega', models.ImageField(blank=True, upload_to='entregas/', verbose_name='Foto de entrega')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones de la entrega')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.envio', verbose_name='Envío confirmado')),
                ('transportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transportista', verbose_name='Transportista que confirmó')),
            ],
            options={
                'verbose_name': 'Confirmación de Entrega',
                'verbose_name_plural': 'Confirmaciones de Entrega',
                'ordering': ['-fecha_confirmacion'],
            },
        ),
    ]
