# Generated by Django 4.2.5 on 2025-12-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transportista_envio_confirmacionentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='stock_oferta',
            field=models.PositiveIntegerField(default=0, help_text='Número de unidades disponibles para esta oferta. 0 = ilimitado', verbose_name='Stock de la oferta'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='unidades_vendidas',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades vendidas'),
        ),
    ]
