# Generated by Django 4.2.5 on 2025-12-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_oferta_stock_oferta_oferta_unidades_vendidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadopagocuenta',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mercadopagocuenta',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
