# Generated by Django 4.2.2 on 2026-02-25 12:25

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_mercadopagocuenta_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carruselimages',
            name='color_fondo',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
        migrations.AlterField(
            model_name='carruselimages',
            name='color_texto',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
