# Generated by Django 5.1.4 on 2026-02-25 14:22

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_carruselimages_color_fondo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carruselimages",
            name="color_fondo",
            field=colorfield.fields.ColorField(
                default="#000000",
                image_field=None,
                max_length=25,
                samples=[("#FFFFFF", "white"), ("#000000", "black")],
            ),
        ),
        migrations.AlterField(
            model_name="carruselimages",
            name="color_texto",
            field=colorfield.fields.ColorField(
                default="#FFFFFF",
                image_field=None,
                max_length=25,
                samples=[("#FFFFFF", "white"), ("#000000", "black")],
            ),
        ),
    ]
