# Generated by Django 4.2.2 on 2026-04-28 17:37

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_carruselimages_color_fondo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Producto Destacado'),
        ),
        migrations.AlterField(
            model_name='carruselimages',
            name='color_fondo',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
        migrations.AlterField(
            model_name='carruselimages',
            name='color_texto',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
