# Generated by Django 4.2.2 on 2026-05-19 13:56

import colorfield.fields
from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_carruselimages_color_fondo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ubicacion',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='Ubicación GPS'),
        ),
        migrations.AlterField(
            model_name='carruselimages',
            name='color_fondo',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
        migrations.AlterField(
            model_name='carruselimages',
            name='color_texto',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
