# Generated by Django 4.2.2 on 2026-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_perfil_ubicacion_alter_carruselimages_color_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación GPS (coordenadas)'),
        ),
    ]
