# Generated by Django 4.2.2 on 2026-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_perfil_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='envio',
            name='tipo_transporte',
            field=models.CharField(choices=[('local', 'Transportista Local'), ('uber', 'Uber Direct')], default='local', max_length=20, verbose_name='Tipo de transporte'),
        ),
        migrations.AddField(
            model_name='envio',
            name='uber_costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo del delivery Uber'),
        ),
        migrations.AddField(
            model_name='envio',
            name='uber_delivery_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de delivery en Uber'),
        ),
        migrations.AddField(
            model_name='envio',
            name='uber_quote_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID de cotización en Uber'),
        ),
        migrations.AddField(
            model_name='envio',
            name='uber_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado en Uber'),
        ),
        migrations.AddField(
            model_name='envio',
            name='uber_tracking_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de tracking de Uber'),
        ),
    ]
