# Generated by Django 5.2.4 on 2025-09-23 13:59

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('knowledge_type', models.CharField(choices=[('product', 'Información de Productos'), ('company', 'Información de la Empresa'), ('policy', 'Políticas y Términos'), ('faq', 'Preguntas Frecuentes'), ('general', 'Información General')], default='general', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(choices=[(1, 'Baja'), (2, 'Media'), (3, 'Alta')], default=1, verbose_name='Prioridad')),
                ('tags', models.CharField(blank=True, help_text='Etiquetas separadas por coma (productos, envíos, garantía, etc.)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conocimiento del Asistente',
                'verbose_name_plural': 'Base de Conocimiento',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssistantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Asistente Virtual', max_length=100, verbose_name='Nombre del Asistente')),
                ('role', models.CharField(choices=[('customer_service', 'Servicio al Cliente'), ('sales', 'Asistente de Ventas'), ('technical', 'Soporte Técnico'), ('general', 'Asistente General'), ('custom', 'Personalizado')], default='customer_service', max_length=50, verbose_name='Rol del Asistente')),
                ('ai_model', models.CharField(choices=[('gpt-4', 'GPT-4'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('claude-2', 'Claude 2'), ('llama-2', 'Llama 2'), ('custom', 'Modelo Personalizado')], default='gpt-3.5-turbo', max_length=50, verbose_name='Modelo de IA')),
                ('custom_model_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Modelo Personalizado')),
                ('system_prompt', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('temperature', models.FloatField(default=0.7, help_text='Controla la creatividad (0.0 - 1.0)', verbose_name='Temperatura')),
                ('max_tokens', models.IntegerField(default=500, help_text='Límite de tokens por respuesta', verbose_name='Máximo de Tokens')),
                ('is_active', models.BooleanField(default=False, help_text='Activar/Desactivar el asistente', verbose_name='Activo')),
                ('knowledge_base_enabled', models.BooleanField(default=True, help_text='Acceso a información de la base de datos', verbose_name='Habilitar Base de Conocimiento')),
                ('product_catalog_access', models.BooleanField(default=True, help_text='Puede consultar información de productos', verbose_name='Acceso a Catálogo')),
                ('order_access', models.BooleanField(default=False, help_text='Puede consultar información de pedidos (solo para usuarios autenticados)', verbose_name='Acceso a Pedidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Asistente',
                'verbose_name_plural': 'Configuraciones de Asistentes',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.assistantconversation')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssistantTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('training_data', models.JSONField(help_text='Datos de entrenamiento en formato JSON')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('training', 'Entrenando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('model_version', models.CharField(max_length=50)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrenamiento',
                'verbose_name_plural': 'Entrenamientos',
            },
        ),
    ]
